Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'Guardfile'

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'config/initializers/devise.rb'

Style/Documentation:
  Exclude:
    - '**/*'
